export const FETCH_BOARDLIST_START = "FETCH_BOARDLIST_START";
export const FETCH_BOARDLIST_FAIL = "FETCH_BOARDLIST_FAIL";
export const FETCH_BOARDLIST_SUCCESS = "FETCH_BOARDLIST_SUCCESS";

export const POST_NEWBOARD_START = "POST_NEWBOARD_START";
export const POST_NEWBOARD_FAIL = "POST_NEWBOARD_FAIL";
export const POST_NEWBOARD_SUCCESS = "POST_NEWBOARD_SUCCESS";

export const POST_NEWCARD_START = "POST_NEWCARD_START";
export const POST_NEWCARD_FAIL = "POST_NEWCARD_FAIL";
export const POST_NEWCARD_SUCCESS = "POST_NEWCARD_SUCCESS";

export const DELETE_BOARD_START = "DELETE_BOARD_START";
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";

export const DELETE_CARD_START = "DELETE_CARD_START";
export const DELETE_CARD_FAIL = "DELETE_CARD_FAIL";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";

export const PUT_CARD_START = "PUT_CARD_START";
export const PUT_CARD_FAIL = "PUT_CARD_FAIL";
export const PUT_CARD_SUCCESS = "PUT_CARD_SUCCESS";

export const PUT_COLOR_START = "PUT_COLOR_START";
export const PUT_COLOR_FAIL = "PUT_COLOR_FAIL";
export const PUT_COLOR_SUCCESS = "PUT_COLOR_SUCCESS";